import { Tour, Destination, Testimonial, BlogPost } from "./types";

export const TOURS: Tour[] = [
  {
    id: "tour-1",
    title: "Swiss Alps Private Helicopter & Ski Expedition",
    category: "Luxury",
    destination: "Swiss Alps",
    country: "Switzerland",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200",
    price: 3450,
    originalPrice: 3900,
    duration: "7 Days",
    rating: 4.9,
    reviews: 124,
    description: "Soar above the iconic Matterhorn in a private helicopter before embarking on an exclusive ski expedition with Olympic guides.",
    dates: ["Aug 12 - Aug 19", "Sep 05 - Sep 12", "Dec 10 - Dec 17"],
    maxGroupSize: 6,
    highlights: ["Private helicopter tour", "Ski-in ski-out luxury chalet", "Michelin-starred dining on peaks", "Exclusive thermal spa access"],
    weatherLocation: "Swiss Alps",
    liveAvailability: 3,
  },
  {
    id: "tour-2",
    title: "Amalfi Coast Yacht Charter & Historical Cliffside Villa",
    category: "Luxury",
    destination: "Amalfi Coast",
    country: "Italy",
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=1200",
    price: 4200,
    originalPrice: 4800,
    duration: "8 Days",
    rating: 4.8,
    reviews: 98,
    description: "Charter a private catamaran across the Tyrrhenian Sea and reside in a historical cliffside villa with sweeping panoramic vistas.",
    dates: ["Jul 24 - Aug 01", "Aug 15 - Aug 23", "Sep 10 - Sep 18"],
    maxGroupSize: 8,
    highlights: ["Private 60ft catamaran cruise", "Chef-prepared coastal lunches", "VIP ancient Pompeii private tour", "Luxury villa with infinity pool"],
    weatherLocation: "Amalfi Coast",
    liveAvailability: 4,
  },
  {
    id: "tour-3",
    title: "Bora Bora Overwater Sanctuary & Coral Conservation",
    category: "Eco-Travel",
    destination: "Bora Bora",
    country: "French Polynesia",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200",
    price: 5100,
    originalPrice: 5900,
    duration: "10 Days",
    rating: 5.0,
    reviews: 82,
    description: "Rejuvenate in an award-winning overwater eco-villa, participate in private coral propagation, and swim with stingrays.",
    dates: ["Aug 01 - Aug 11", "Sep 14 - Sep 24", "Oct 05 - Oct 15"],
    maxGroupSize: 4,
    highlights: ["Ultra-luxury overwater glass-floor villa", "Coral reef restoration program", "Private manta ray snorkeling safari", "Sunset Polynesian canoe dinner"],
    weatherLocation: "Bora Bora",
    liveAvailability: 2,
  },
  {
    id: "tour-4",
    title: "Kyoto Autumn Forest & Temple Zen Exploration",
    category: "Cultural",
    destination: "Kyoto",
    country: "Japan",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=1200",
    price: 2800,
    originalPrice: 3200,
    duration: "6 Days",
    rating: 4.95,
    reviews: 145,
    description: "Immerse in the breathtaking gold and crimson foliage of Kyoto. Participate in private Zen tea ceremonies and sacred temple tours.",
    dates: ["Oct 20 - Oct 26", "Nov 10 - Nov 16", "Nov 22 - Nov 28"],
    maxGroupSize: 10,
    highlights: ["Private night-access temple tour", "Authentic Kaiseki 12-course banquet", "Traditional tea ceremony with Geisha", "Bamboo forest private walk"],
    weatherLocation: "Kyoto",
    liveAvailability: 5,
  },
  {
    id: "tour-5",
    title: "Iceland Volcanic Glaciers & Northern Lights Odyssey",
    category: "Adventure",
    destination: "Reykjavik",
    country: "Iceland",
    image: "https://images.unsplash.com/photo-1504893524553-ac55fce698be?q=80&w=1200",
    price: 3100,
    originalPrice: 3600,
    duration: "7 Days",
    rating: 4.75,
    reviews: 110,
    description: "Venture inside crystal ice caves, scale active black-sand volcanic dunes, and view the aurora borealis from a geothermal dome.",
    dates: ["Sep 18 - Sep 25", "Oct 12 - Oct 19", "Nov 02 - Nov 09"],
    maxGroupSize: 8,
    highlights: ["Superjeep volcanic highland tour", "Geothermal hot spring private pool", "Ice cave glacier trekking", "Aurora hunting with expert astronomers"],
    weatherLocation: "Reykjavik",
    liveAvailability: 1,
  },
  {
    id: "tour-6",
    title: "Serengeti Golden Savanna & Eco-Luxury Safari",
    category: "Adventure",
    destination: "Serengeti",
    country: "Tanzania",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?q=80&w=1200",
    price: 4900,
    originalPrice: 5500,
    duration: "9 Days",
    rating: 4.9,
    reviews: 73,
    description: "Witness the Great Migration from a hot air balloon, stay in an eco-luxury canopy lodge, and track leopards with Maasai rangers.",
    dates: ["Aug 05 - Aug 14", "Sep 02 - Sep 11", "Oct 18 - Oct 27"],
    maxGroupSize: 6,
    highlights: ["Maasai-led preservation walk", "Sunrise balloon flight over migrating herds", "Solar-powered canvas luxury camps", "4x4 game drives with master tracker"],
    weatherLocation: "Serengeti",
    liveAvailability: 3,
  },
];

export const DESTINATIONS: Destination[] = [
  {
    id: "dest-1",
    name: "Swiss Alps",
    country: "Switzerland",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1200",
    description: "Majestic snow-capped alpine peaks, sparkling pristine lakes, and legendary ski chalets.",
    rating: 4.9,
    priceFrom: 3450,
    coordinates: { x: 48, y: 35 },
  },
  {
    id: "dest-2",
    name: "Amalfi Coast",
    country: "Italy",
    image: "https://images.unsplash.com/photo-1424514287761-1a3b1792ec0f?q=80&w=1200",
    description: "Spectacular dramatic cliffs, vibrant pastel harbors, and legendary Mediterranean cuisine.",
    rating: 4.8,
    priceFrom: 4200,
    coordinates: { x: 50, y: 40 },
  },
  {
    id: "dest-3",
    name: "Bora Bora",
    country: "French Polynesia",
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?q=80&w=1200",
    description: "Emerald volcanic hills dropping into a breathtaking, multi-colored turquoise lagoon.",
    rating: 5.0,
    priceFrom: 5100,
    coordinates: { x: 18, y: 70 },
  },
  {
    id: "dest-4",
    name: "Kyoto",
    country: "Japan",
    image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=1200",
    description: "Ethereal ancient temples, lush bamboo forests, and magnificent traditional tea cultures.",
    rating: 4.95,
    priceFrom: 2800,
    coordinates: { x: 82, y: 43 },
  },
  {
    id: "dest-5",
    name: "Reykjavik",
    country: "Iceland",
    image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?q=80&w=1200",
    description: "A cosmic wonderland of black basalt beaches, steaming geothermal lagoons, and dancing lights.",
    rating: 4.75,
    priceFrom: 3100,
    coordinates: { x: 42, y: 22 },
  },
  {
    id: "dest-6",
    name: "Serengeti",
    country: "Tanzania",
    image: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?q=80&w=1200",
    description: "Immense golden savannas teeming with magnificent wildlife and ancient acacia silhouettes.",
    rating: 4.9,
    priceFrom: 4900,
    coordinates: { x: 55, y: 65 },
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "test-1",
    name: "Lady Alexandra Sterling",
    role: "Philanthropist & Explorer",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=200",
    rating: 5,
    text: "The bespoke helicopter expedition in Switzerland exceeded every dream. NaturO coordinates the impossible with extraordinary discretion and flawless style.",
    location: "London, UK",
  },
  {
    id: "test-2",
    name: "Dr. Marcus Vance",
    role: "Conservation Biologist",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200",
    rating: 5,
    text: "Participating in coral propagation in Bora Bora while staying in such ethical, top-tier luxury was deeply meaningful. Perfect harmony of luxury and sustainability.",
    location: "Boston, USA",
  },
  {
    id: "test-3",
    name: "Ami & Jin Sato",
    role: "Luxury Travel Curators",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=200",
    rating: 5,
    text: "NaturO handles experiential tourism on a completely elevated level. Our private villa over the Amalfi Coast felt like floating inside a classic painting.",
    location: "Tokyo, Japan",
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "blog-1",
    title: "The Future of Eco-Luxe Travel: Harmony Over Compromise",
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?q=80&w=1200",
    date: "June 15, 2026",
    readTime: "5 min read",
    category: "Eco-Luxe",
    author: "Elena Rostov",
    excerpt: "How modern high-end resorts are pioneering massive carbon-neutral initiatives and local wildlife protection without losing an ounce of luxury.",
  },
  {
    id: "blog-2",
    title: "Chasing Auroras: An Expert's Visual Guide to Iceland",
    image: "https://images.unsplash.com/photo-1529963183134-61a90db47eaf?q=80&w=1200",
    date: "July 02, 2026",
    readTime: "7 min read",
    category: "Adventure",
    author: "Kai Thorvaldsen",
    excerpt: "Our veteran astronomy guide reveals the absolute best isolated locations and photographic settings to capture the magnificent northern lights.",
  },
  {
    id: "blog-3",
    title: "Secluded Kyoto: Unveiling Hidden Mountain Temples",
    image: "https://images.unsplash.com/photo-1490730141103-6cac27aaab94?q=80&w=1200",
    date: "July 18, 2026",
    readTime: "4 min read",
    category: "Culture",
    author: "Kenji Takahashi",
    excerpt: "Escape the bustling tourist lines with this handpicked itinerary of ancient wooden temples quietly tucked away in Kyoto's sacred northern ridge.",
  },
];
